from backend.app.core.config import (
    KAFKA_BOOTSTRAP_SERVERS,
    KAFKA_TOPIC,
    KAFKA_CONSUMER_GROUP,
    PRODUCER_MAX_TRANSACTIONS,
    CONSUMER_MAX_TRANSACTIONS,
    PRODUCER_INTERVAL_SECONDS
)